on: push
name: deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Деплой
        uses: pressidium/lftp-mirror-action@v1
      
        with:
          host: ${{ secrets.SFTP_URL }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          localDir: '.'
          remoteDir: './krutyak'
          reverse: true
